In [1]:
import numpy as np

In [2]:
X1=np.array([1,1,1,1,1,2,2,2,2,2,3,3,3,3,3])
X2=np.array(['S','M','M','S','S','S','M','M','L','L','L','M','M','L','L'])
y=np.array([-1,-1,1,1,-1,-1,-1,1,1,1,1,1,1,1,-1])

In [4]:
PX1_1=np.zeros(3)
PX2_1=np.zeros(3)
PX1_n1=np.zeros(3)
PX2_n1=np.zeros(3)
Py=np.zeros(2)
v=1

In [8]:
#计算P(y=-1)与P(y=1)
print(np.unique(y))
for i in range(len(np.unique(y))):
    Py[i]=((y==np.unique(y)[i]).sum()+v)/(len(y)+2*v)
print(Py)

[-1  1]
[0.41176471 0.58823529]


In [9]:
#计算P(x=1,2,3|y=1)
print(np.unique(X1))
for i in range(len(np.unique(X1))):
    PX1_1[i]=((X1[y==1]==np.unique(X1)[i]).sum()+v)/((y==1).sum()+3*v)
print(PX1_1)

[1 2 3]
[0.25       0.33333333 0.41666667]


In [12]:
#计算P(x='S','M','L'|y=1)
print(np.unique(X2))
for i in range(len(np.unique(X1))):
    PX2_1[i]=((X2[y==1]==np.unique(X2)[i]).sum()+v)/((y==1).sum()+3*v)
print(PX2_1)

['L' 'M' 'S']
[0.41666667 0.41666667 0.16666667]


In [11]:
#计算P(x=1,2,3|y=-1)
print(np.unique(X1))
for i in range(len(np.unique(X1))):
    PX1_n1[i]=((X1[y==-1]==np.unique(X1)[i]).sum()+v)/((y==-1).sum()+3*v)
print(PX1_n1)

[1 2 3]
[0.44444444 0.33333333 0.22222222]


In [10]:
#计算P(x='S','M','L'|y=-1)
print(np.unique(X2))
for i in range(len(np.unique(X1))):
    PX2_n1[i]=((X2[y==-1]==np.unique(X2)[i]).sum()+v)/((y==-1).sum()+3*v)
print(PX2_n1)

['L' 'M' 'S']
[0.22222222 0.33333333 0.44444444]


In [13]:
#预测x=[2,S]
x=np.array([2,'S'])
PXIs1=Py[1]*PX1_1[1]*PX2_1[2]
PXIsn1=Py[0]*PX1_n1[1]*PX2_n1[2]
print('The Possibility Of x is the class 1 is '+str(PXIs1))
print('The Possibility Of x is the class -1 is '+str(PXIsn1))
print('Because the possibility of 1 less than the possibity of -1,so x is most possible of class -1')

The Possibility Of x is the class 1 is 0.0326797385620915
The Possibility Of x is the class -1 is 0.06100217864923746
Because the possibility of 1 less than the possibity of -1,so x is most possible of class -1
